stages:
  - deploy
before_script:
  - "which ssh-agent || (apt-get update -y && apt-get install -y openssh-client)"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - pwd && ls
    - git remote add staging ssh://staging.effortless.dk:22022/srv/git/EffortlessBackend.git
    - git push staging master
  environment:
    name: staging
    url: https://staging.effortless.dk
  only: 
  - master
deploy_production:
  stage: deploy
  script:
    - echo "Deploying to master server..."
    - git remote add production ssh://api.effortless.dk:22022/srv/git/EffortlessBackend.git
    - git push production master
  environment:
    name: production
    url: https://effortless.dk
  when: manual
  only:
  - master