version: "3"
services:
  api:
    build: ./EffortlessApi
    ports:
      - "5000:80"
    # volumes:
    #   - ./EffortlessApi:/App
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"