version: '3'
# volumes:
#   datafiles:
services:
  restapi:
    build:
      context: ./EffortlessApi
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always
    environment:
      - DB_HOST=db
      - ASPNETCORE_ENVIRONMENT=Development
  db:
   image: postgres
   ports:
     - "5432:5432"
  #  volumes: 
  #   - datafiles:/var/lib/postgres
   restart: always
   environment:
     POSTGRES_USER: "root"
     POSTGRES_PASSWORD: "root"